# This is the main Docker Compose configuration file.
# It defines and configures the services needed to run the application in a container.
# The "web" service is responsible for running the Flask application.

version: "3.9"
services:
  web:
    image: first-rest-api
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/rest_api_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: rest_api_db
    ports:
      - "5432:5432"
