# This is the main Docker Compose configuration file.
# It defines and configures the services needed to run the application in a container.
# The "web" service is responsible for running the Flask application.

version: "3"
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost/rest_api_db
    depends_on:
      - db
    env_file:
      - .\.env

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    env_file:
      - .\.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: