"""empty message

Revision ID: 176dee29d2c5
Revises: dbfc22acff69
Create Date: 2025-04-23 05:39:28.254867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176dee29d2c5'
down_revision = 'dbfc22acff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
